import { useState } from 'react';
import { Slider } from '@/components/ui/Slider';
import { Switch } from '@/components/ui/Switch';

export function GeneralTab() {
  const [temp, setTemp] = useState(0.7);
  const [ctx, setCtx] = useState(128000);
  const [maxOut, setMaxOut] = useState(8192);
  const [autoCommit, setAutoCommit] = useState(true);
  const [autoPush, setAutoPush] = useState(false);
  const [autoupdate, setAutoupdate] = useState(true);
  const [telemetry, setTelemetry] = useState(false);

  return (
    <div className="grid grid-cols-1 gap-5 lg:grid-cols-2">
      <Card title="Model defaults">
        <SliderRow
          label="Temperature"
          value={temp}
          min={0}
          max={2}
          step={0.05}
          format={(v) => v.toFixed(2)}
          onChange={setTemp}
        />
        <SliderRow
          label="Context window"
          value={ctx}
          min={8000}
          max={1000000}
          step={1000}
          format={(v) => (v >= 1000 ? `${Math.round(v / 1000)}K` : `${v}`)}
          onChange={setCtx}
        />
        <SliderRow
          label="Max output tokens"
          value={maxOut}
          min={256}
          max={32000}
          step={256}
          format={(v) => `${v}`}
          onChange={setMaxOut}
        />
      </Card>

      <Card title="Workflow">
        <Toggle
          label="Auto-commit after each plan step"
          description="Conventional Commits message generated by the agent."
          checked={autoCommit}
          onChange={setAutoCommit}
        />
        <Toggle
          label="Auto-push to remote"
          description="Push after every successful step."
          checked={autoPush}
          onChange={setAutoPush}
        />
        <Toggle
          label="Auto-update Kedex"
          description="Check for new versions on launch."
          checked={autoupdate}
          onChange={setAutoupdate}
        />
        <Toggle
          label="Send anonymous telemetry"
          description="Helps KebiLab improve the product."
          checked={telemetry}
          onChange={setTelemetry}
        />
      </Card>

      <Card title="Security" className="lg:col-span-2">
        <Toggle
          label="Always require approval for shell commands"
          description="The agent pauses before running `npm install`, `git push`, `rm`, etc."
          checked
          onChange={() => {}}
        />
        <Toggle
          label="Allow read-only commands automatically"
          description="`ls`, `cat`, `find` run without confirmation."
          checked
          onChange={() => {}}
        />
        <Toggle
          label="Run in isolated git worktree"
          description="Agent edits a copy of the repo. You merge when ready."
          checked
          onChange={() => {}}
        />
      </Card>
    </div>
  );
}

function Card({
  title,
  children,
  className,
}: {
  title: string;
  children: React.ReactNode;
  className?: string;
}) {
  return (
    <div className={`rounded-xl border border-line bg-bg p-4 ${className ?? ''}`}>
      <div className="mb-3 text-sm font-medium text-fg">{title}</div>
      <div className="space-y-3">{children}</div>
    </div>
  );
}

function SliderRow({
  label,
  value,
  min,
  max,
  step,
  format,
  onChange,
}: {
  label: string;
  value: number;
  min: number;
  max: number;
  step: number;
  format: (v: number) => string;
  onChange: (v: number) => void;
}) {
  return (
    <div>
      <div className="mb-1.5 flex items-center justify-between">
        <span className="text-xs text-fg">{label}</span>
        <span className=" text-2xs text-fg-dim">{format(value)}</span>
      </div>
      <Slider value={value} min={min} max={max} step={step} onChange={onChange} />
    </div>
  );
}

function Toggle({
  label,
  description,
  checked,
  onChange,
}: {
  label: string;
  description?: string;
  checked: boolean;
  onChange: (b: boolean) => void;
}) {
  return (
    <div className="flex items-start justify-between gap-3 rounded-md border border-line bg-bg-1 px-3 py-2.5">
      <div>
        <div className="text-xs text-fg">{label}</div>
        {description && <div className="mt-0.5 text-2xs text-fg-dim">{description}</div>}
      </div>
      <Switch checked={checked} onCheckedChange={onChange} />
    </div>
  );
}
